version: '3.9'

services:
  sql:
    build:
      context: ./db
      dockerfile: Dockerfile.sql  # Reference the Dockerfile.sql for custom build
    container_name: buildtrack_db
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql


  app:
    environment:
      CORS_HOST: ${PUBLIC_URL}
      DATABASE_URL: "mssql+pymssql://sa:${SA_PASSWORD}@sql:1433/buildtrack"
    build:
      context: app
    ports:
      - "8000:80"
    container_name: buildtrack_app
    volumes:
      - ./app:/app
    restart: always
    depends_on:
      - sql


  ghi:
    build: ./buildtrack
    container_name: buildtrack_ghi
    working_dir: /app
    volumes:
      - ./buildtrack:/app
    ports:
      - "3000:3000"
    depends_on:
      - app
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: ${PUBLIC_URL}
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
    restart: always
  
  adminer:
    image: adminer
    container_name: buildtrack_adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  sql_data:
    driver: local
